# _config.yml

title: Baby Feelings
description: AIで赤ちゃんの気持ち、もっとわかる。
baseurl: "https://baby-feelings.github.io/" # GitHub Pagesでルートにデプロイする場合は空のまま
url: "" # 公開先のURL（例: https://Yuki-baby.github.io/baby-feelings.github.io）